version: "3.9"

services:
  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'rainbow-umbrella'
      MYSQL_ROOT_PASSWORD: 'example'
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"

